let
    Source = Excel.Workbook(File.Contents("__________FILEPATH__________"), null, true),
    Navigation = Source{0}[Data],
    #"Changed Type" = Table.TransformColumnTypes(Navigation,{{"Column1", type text}, {"Column2", type any}, {"Column3", type any}, {"Column4", type any}, {"Column5", type any}, {"Column6", type any}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}}),
    #"Removed Top Rows" = Table.Skip(#"Changed Type",4),
    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Employee ID", type text}, {"Worker", type text}, {"Hire Date", type date}, {"Termination Date", type date}, {"Date and Time Initiated", type date}, {"Date and Time Completed", type date}, {"Is Rehire", type text}, {"Terminated (based on report date)", type text}, {"Business Title", type text}, {"Phone - Primary Work", type text}, {"Email - Work", type text}, {"Workday Account", type text}, {"User Name", type text}, {"Sector", type text}, {"Business Unit & Function", type text}, {"Primary Work Address - Country", type text}, {"Location", type text}, {"Company", type text}, {"Manager", type text}, {"Worker Type", type text}, {"Employee Type", type text}}),
    #"Grouped Rows" = Table.Group(#"Changed Type1", {"Employee ID"}, {{"Count", each Table.RowCount(_), type number}, {"Drilldown", each _, type table}}),
    #"Expanded Drilldown" = Table.ExpandTableColumn(#"Grouped Rows", "Drilldown", {"Employee ID", "Worker", "Hire Date", "Termination Date", "Date and Time Initiated", "Date and Time Completed", "Is Rehire", "Terminated (based on report date)", "Business Title", "Phone - Primary Work", "Email - Work", "Workday Account", "User Name", "Sector", "Business Unit & Function", "Primary Work Address - Country", "Location", "Company", "Manager", "Worker Type", "Employee Type"}, {"Employee ID.1", "Worker", "Hire Date", "Termination Date", "Date and Time Initiated", "Date and Time Completed", "Is Rehire", "Terminated (based on report date)", "Business Title", "Phone - Primary Work", "Email - Work", "Workday Account", "User Name", "Sector", "Business Unit & Function", "Primary Work Address - Country", "Location", "Company", "Manager", "Worker Type", "Employee Type"}),
    #"Removed Columns" = Table.RemoveColumns(#"Expanded Drilldown",{"Employee ID.1"}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Removed Columns",{{"Date and Time Completed", type date}, {"Date and Time Initiated", type date}, {"Termination Date", type date}, {"Hire Date", type date}, {"Worker", type text}, {"Is Rehire", type text}, {"Terminated (based on report date)", type text}, {"Business Title", type text}, {"Phone - Primary Work", type text}, {"Email - Work", type text}, {"Workday Account", type text}, {"User Name", type text}, {"Sector", type text}, {"Business Unit & Function", type text}, {"Primary Work Address - Country", type text}, {"Location", type text}, {"Company", type text}, {"Manager", type text}, {"Worker Type", type text}, {"Employee Type", type text}}),
    #"Sorted Rows" = Table.Sort(#"Changed Type2",{{"Employee ID", Order.Ascending}, {"Date and Time Completed", Order.Descending}}),
    #"Buffered Table" = Table.Buffer(#"Sorted Rows"),
    #"Removed Duplicates" = Table.Distinct(#"Buffered Table", {"Employee ID"})
in
    #"Removed Duplicates"
